import React from 'react';
import './ReportsTrackingScheduling.css';

const ReportsTrackingScheduling = () => {
  return (
    <div className="reports-tracking-scheduling">
      <h1>Reports, Tracking & Scheduling</h1>
      <p>View reports, track progress, and manage scheduling</p>
      
      <div className="reports-actions">
        <button className="primary-button">Generate Report</button>
        <button className="secondary-button">View Calendar</button>
      </div>
      
      <div className="reports-sections">
        <div className="section">
          <h2>Reports Review</h2>
          <div className="section-content">
            <p>View academic and administrative reports</p>
            <button className="action-button">View Reports</button>
          </div>
        </div>
        
        <div className="section">
          <h2>Progress Tracking</h2>
          <div className="section-content">
            <p>Monitor teacher activity and class progress</p>
            <button className="action-button">Track Progress</button>
          </div>
        </div>
        
        <div className="section">
          <h2>Login/Logout Tracking</h2>
          <div className="section-content">
            <p>Track system usage by all users</p>
            <button className="action-button">View Logs</button>
          </div>
        </div>
        
        <div className="section">
          <h2>Calendar & Scheduling</h2>
          <div className="section-content">
            <p>Manage academic calendar, events, and deadlines</p>
            <button className="action-button">Manage Calendar</button>
          </div>
        </div>
      </div>
      
      <div className="reports-table">
        <h2>Recent Reports</h2>
        <table>
          <thead>
            <tr>
              <th>Report Name</th>
              <th>Type</th>
              <th>Generated By</th>
              <th>Date</th>
              <th>Status</th>
              <th>Actions</th>
            </tr>
          </thead>
          <tbody>
            <tr>
              <td>Monthly Usage Report</td>
              <td>System</td>
              <td>Admin System</td>
              <td>2023-05-01</td>
              <td>Completed</td>
              <td>
                <button className="action-button">View</button>
                <button className="action-button">Download</button>
              </td>
            </tr>
            <tr>
              <td>Student Performance Report</td>
              <td>Academic</td>
              <td>John Doe</td>
              <td>2023-05-10</td>
              <td>Completed</td>
              <td>
                <button className="action-button">View</button>
                <button className="action-button">Download</button>
              </td>
            </tr>
          </tbody>
        </table>
      </div>
    </div>
  );
};

export default ReportsTrackingScheduling;